### ISSUE TITLE
Regelen back-up in Ierland (disaster recovery)

### ISSUE THREAD

**Issue by marnixdessing** [GemeenteNijmegen/geo-storage#14]

**Comment by wvdeeckhout** [comment]
@marnixdessing voegt deze toe aan de backup epic

**Comment by marnixdessing** [comment]
Backup op acceptatie gerealiseerd: 
- Replicatie naar buckets in andere region
- Testen van batch job replication voor backup van nu bestaande files.

Nog uit te rollen naar productie en daar op batch jobs te draaien.

**Comment by marnixdessing** [comment]
Replication uitgerold, batch jobs draaien lukt nog niet.

**Comment by marnixdessing** [comment]
Ik maak eerst voor alle buckets inventory reports aan, dit duurt 48 uur...

**Comment by marnixdessing** [comment]
Inventory reports zijn aangemaakt en worden dagelijks gegenereerd. PR om rechten goed te zetten voor backup-replication-role is aangemaakt. Stappen die nog nodig zijn:
- Kopieren objecten naar zelfde bucket (nieuwe versie, versleuteld met nieuwe KMS key)
- Batch job draaien voor replicatie van objecten die nu met de nieuwe key zijn versleuteld
- Done?

**Comment by marnixdessing** [comment]
Sommige objecten hebben nog geen version ID, hier gaat het fout met de manifest CSV die wordt gegenereerd door AWS S3 Inventory. Kijken of we de CSV kunnen aanpassen en formatteren zodat we die versie kunnen gebruiken...

**Comment by marnixdessing** [comment]
Backup zou nu moeten werken, even 2 dagen wachten tot de oude versies zijn verwijderd. Dan kunnen we de replicatie van bestaande objecten doorvoeren.

**Comment by marnixdessing** [comment]
Dit heeft iets meer gekost dan 4 uur, maar is nu ingeregeld en werkt cross-account.
