### ISSUE TITLE
Overladen data Azure naar AWS GemeenteNijmegen

### ISSUE THREAD

**Issue by MartijnvDijk** [GemeenteNijmegen/geo-storage#206]
Mail van Freek. Credentials nodig om uit te zoeken waarom bepaalde metadata mist. FME naar s3 connectie.

Vraag is of dit even kan wachten op Marnix?
Of dat we deze credentials aan Freek gaan geven?

**Comment by marnixdessing** [comment]
Freek heeft dit al op kunnen lossen. Ik heb wat extra documentatie geschreven over hoe user credential aan te maken.
